Создает моковые данные и отрисовывает их в шаблонах
htmlacademy-ecmascript/703335-big-trip-14 pull request #4
Opened 2021-04-13 00:02 UTC by Bencivenga

2021-04-13 10:16 UTC, rideorgtfo requested changes

2021-04-13 10:16 UTC, rideorgtfo commented on src/data.js
> +    isChecked: Boolean(getRandomInteger(0, 1)),
Так не совсем корректно делать. Все-таки выбранные предложения у каждой точки свои

2021-04-13 10:16 UTC, rideorgtfo commented on src/data.js
> +];
Зачем много объектов? Ссылка одна, при генерации подставляй уникальную чиселку

2021-04-13 10:16 UTC, rideorgtfo commented on src/main.js
> +  render(tripList, createRoutePointTemplate(routePoints[i]));
Дважды одна точка рисуется. В задании написано отрисовать 0 формой редактирования (она же форма создания) и остальные просмотром

2021-04-13 10:16 UTC, rideorgtfo commented on src/util.js
> +  return newArray;
Предлагаю использовать filter, получится гораздо короче и декларативнее

2021-04-13 10:16 UTC, rideorgtfo commented on src/util.js
> +  return description.join(' ');
Это не случайные предложения. В твоем решении они всегда берутся подряд.

2021-04-13 10:16 UTC, rideorgtfo commented on src/util.js
> +  const date = dayjs(dayjs(start) + Math.random() * (dayjs(end) - dayjs(start)));
А расскажи почему так? Совсем непонятно что тут происходит

2021-04-13 10:16 UTC, rideorgtfo commented on src/util.js
> +  minutes = (minutes < 10) ? `0${minutes}` : minutes;
Используй padStart

2021-04-13 10:16 UTC, rideorgtfo commented on src/util.js
> +  return `${days}D ${hours}H ${minutes}M`;
Можно упростить условия.
```
  if (days > 0) {
    return `${days}D ${hours}H ${minutes}M`;
  }
  
  if (hours > 0) {
    return `${hours}H ${minutes}M`;
  }
  
  return `${minutes}M`;
```

2021-04-13 10:16 UTC, rideorgtfo commented on src/view/edit-form.js
> +  const createOffers = (offers) => {
Можно вынести функцию на уровень модуля

2021-04-13 10:16 UTC, rideorgtfo commented on src/view/edit-form.js
> +    return (offers === null || offers.length === 0) ? '' :
Эта проверка не нужна

2021-04-13 10:16 UTC, rideorgtfo commented on src/view/edit-form.js
> +  const createOffers = (offers) => {
Ниже аналогичные случаи

2021-04-13 10:16 UTC, rideorgtfo commented on src/view/edit-form.js
> +    return (offers === null || offers.length === 0) ? '' :
Ниже аналогичные случаи

2021-04-13 10:16 UTC, rideorgtfo commented on src/view/filters.js
> +  const {name, count} = filters;
Кажется это filter, а не filters

2021-04-13 10:16 UTC, rideorgtfo commented on src/mock/route-point.js
> +    offers: offers.get(type) || null,
В качестве значения по-умолчанию лучше использовать пустой массив, чтобы не делать лишних проверок

2021-04-18 15:18 UTC, Bencivenga commented on src/util.js
> +  const date = dayjs(dayjs(start) + Math.random() * (dayjs(end) - dayjs(start)));
Берется текущая дата (start), к ней в вызове этой функции добавляется 6 месяцев (end). Таким образом возвращается рандомная дата с интервалом текущая дата + 6 месяцев

2021-04-21 09:49 UTC, rideorgtfo requested changes

2021-04-21 09:49 UTC, rideorgtfo commented on src/util.js
> +  const date = dayjs(dayjs(start) + Math.random() * (dayjs(end) - dayjs(start)));
Дату\время можно представить в виде timestamp. В результате твоя задача сводится к вычислению случайного числа в интервале.
```
const startTimestamp = Number(dayjs(start);
const endTimestamp = Number(dayjs(start).add(6, 'month'))
const date = dayjs(getRandomInteger(startTimestamp, endTimestamp))
```

2021-04-21 09:49 UTC, rideorgtfo commented on src/util.js
> +  return (offers.length === 0) ? '' :
Эта проверка не нужна. Если массив будет пустым, map вернет пустой массив. А join пустого массива это пустая строка.

2021-04-21 09:49 UTC, rideorgtfo commented on src/view/edit-form.js
> +  const createDescription = (info) => {
Нужно вынести функцию на уровень модуля

2021-04-21 09:49 UTC, rideorgtfo commented on src/view/make-form.js
> +  };
На уровень модуля

2021-04-21 09:49 UTC, rideorgtfo commented on src/view/make-form.js
> +  const createDescription = (info) => {
На уровень модуля

2021-04-21 09:49 UTC, rideorgtfo commented on src/view/route-point.js
> +    return (offers.length === 0) ? '' :
Лишняя проверка

2021-04-21 09:49 UTC, rideorgtfo commented on src/view/route-point.js
> +  const createOffers = (offers) => {
На уровень модуля

2021-04-21 12:46 UTC, merged